Update pr-pusher.yml

diff --git a/.github/workflows/pr-pusher.yml b/.github/workflows/pr-pusher.yml
--- a/.github/workflows/pr-pusher.yml
+++ b/.github/workflows/pr-pusher.yml
@@ -23,17 +23,29 @@ jobs:
           GEN_FILE="lib/src/icons/next_flutter_icons.dart"
           ASSETS_DIR="${{ github.workspace }}/assets/"
 
-          ZIP_FILES=$(find $ASSETS_DIR -type f -name "*.zip")
+          EXPECTED_NAMES=("bold.svg" "broken.svg" "bulk.svg" "linear.svg" "outline.svg" "twotone.svg")
+          EXPECTED_FILES=${#EXPECTED_NAMES[@]}
 
-          # if [ -z "$ZIP_FILES" ]; then
-          #   echo "No .zip file found in assets. Nothing needs to be processed"
-          #   exit 0
-          # fi
+          ZIP_FILES=$(find $ASSETS_DIR -type f -name "*.zip")
           
           for ZIP_FILE in $ZIP_FILES; do
             FOLDER_NAME=$(basename -s.zip "$ZIP_FILE")
             mkdir -p $ASSETS_DIR/$FOLDER_NAME/
             unzip "$ZIP_FILE" -d $ASSETS_DIR/$FOLDER_NAME
+
+            SVGS=$(ls $ASSETS_DIR/$FOLDER_NAME/)
+
+            if [ "$EXTRACTED_FILES" != "5" ]; then
+              echo "Expected $EXPECTED_FILES files, but found $EXTRACTED_FILES."
+              exit 1
+            fi
+
+            for FILE in "${EXPECTED_NAMES[@]}"; do
+              if! ls $ASSETS_DIR | grep -q "^$FILE$"; then
+                echo "Missing file: $FILE"
+                exit 1
+              fi
+            done
             
             rm "$ZIP_FILE"
           done
@@ -61,7 +73,6 @@ jobs:
             ENUM_DEFINITION+="  $ENUM_CASE,"
           done
           
-          # Close the enum definition
           ENUM_DEFINITION+=";const NextIcons(super.basePath);}"
           
           # Output the generated enum definition
